services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3033:3033'
      - '3034:3034'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: